mention version scheme in readme
oracle/opengrok pull request #3255
Opened 2020-10-02 21:54 UTC by tulinkry

I added a note about opengrok version meaning when doing an update

2020-10-03 00:33 UTC, idodeclare requested changes

2020-10-03 00:33 UTC, idodeclare commented on README.md
> +OpenGrok uses [semantic versioning](https://semver.org/) and the version components further tells more details about updating to newer version. The version scheme is x.y.z and change in any component
Maybe better as "tell"?

2020-10-05 13:59 UTC, tulinkry commented on README.md
> +OpenGrok uses [semantic versioning](https://semver.org/) and the version components further tells more details about updating to newer version. The version scheme is x.y.z and change in any component
indicates

2020-10-05 14:21 UTC, vladak commented on README.md
> + - z - redeployment of the web application is necessary
not in all the cases

2020-10-05 15:13 UTC, tulinkry commented on README.md
> + - z - redeployment of the web application is necessary
the wiki says only:

> If only z changes, just redeploy new web application and keep going.

2020-10-05 15:24 UTC, vladak commented on README.md
> + - z - redeployment of the web application is necessary
That's recommended, not necessary.

2020-10-05 21:34 UTC, vladak commented on README.md
> + - z - redeployment of the web application is necessary
```suggestion
 - z - redeploy web application
```

2020-10-06 08:20 UTC, merged

2020-10-06 08:28 UTC, tulinkry commented on README.md
> + - z - redeployment of the web application is necessary
ah ok