Use annotations instead of declarations in web.xml
oracle/opengrok pull request #3326
Opened 2020-10-27 14:16 UTC by ahornace

Using annotations is much more popular nowadays than declaring things in xml files. Therefore, I thought that this might be a good step forward.

I do not know how to deal with the jsp servlets properly so I left them be for the time being.

If you do not like this approach, then feel free to close :)

Thanks.

2020-10-27 14:31 UTC, vladak commented
Not thrilled. To me, being able to configure the order and the parameters in one place is making the administration more transparent.

2020-10-27 14:35 UTC, tulinkry commented
I agree but this is the future old man!

2020-10-29 10:11 UTC, vladak commented
Fair enough :-) How does one configure the parameters in the new world ? Looks like https://github.com/oracle/opengrok/wiki/Webapp-configuration#changing-webapp-parameters will need to be updated.

2020-10-29 10:13 UTC, vladak requested changes
I'd like to see a test case that checks the ordering of the filters.

2020-10-29 10:40 UTC, ahornace commented
> How does one configure the parameters in the new world ?

I think the same way as before. `@WebListener` does not have any attributes for that but even if it did, it would still pose a problem for our purposes since recompilation would be needed.

> I'd like to see a test case that checks the ordering of the filters.

It seems that Servlet 3.x API does not allow this. Maybe 4.x fixed this issue which is available in Tomcat 9.x but I don't know. 
https://stackoverflow.com/questions/6560969/how-to-define-servlet-filter-order-of-execution-using-annotations-in-war

2020-10-29 10:46 UTC, vladak commented
> > I'd like to see a test case that checks the ordering of the filters.
> 
> It seems that Servlet 3.x API does not allow this. Maybe 4.x fixed this issue which is available in Tomcat 9.x but I don't know.
> https://stackoverflow.com/questions/6560969/how-to-define-servlet-filter-order-of-execution-using-annotations-in-war

what about https://docs.oracle.com/javaee/7/api/javax/ws/rs/Priorities.html ?

2020-10-29 10:48 UTC, ahornace commented
> what about https://docs.oracle.com/javaee/7/api/javax/ws/rs/Priorities.html ?

That is from jax-rs project (REST) instead of `javax.servlet` so I don't think they will work together :/

2021-02-25 01:05 UTC, closed without merging