Remove helix-p4d from install list
oracle/opengrok pull request #4520
Opened 2023-12-25 02:07 UTC by parheliamm

helix-p4d didn't available on ARM64 platform,
there is no obvious impacts after checking docker image on ARM64

After this change, docker image created successfully on ARM64 platform.

2023-12-25 19:13 UTC, vladak requested changes
This will remove Perforce from x86 image,  though. Is there a way how to make it optional ?

2023-12-26 04:11 UTC, parheliamm commented
> This will remove Perforce from x86 image, though. Is there a way how to make it optional ?

The  new patches detect the architecture during docker image build stage.
If ARM64 found, skip install helix-p4d only.

2023-12-26 10:41 UTC, vladak commented
Ack, need to have your OCA on file before this can go in.

2023-12-26 14:17 UTC, parheliamm commented
> Ack, need to have your OCA on file before this can go in.

OCA is under reviewing, it might be passed in coming days.

2024-01-02 12:18 UTC, vladak commented
Seems like the Docker image linter complains about the multiple RUNs. The error can be suppressed.

2024-01-02 23:41 UTC, parheliamm commented
> Seems like the Docker image linter complains about the multiple RUNs. The error can be suppressed.

Do I need to check the the failure issue and fix it?

2024-01-03 09:53 UTC, vladak commented
> > Seems like the Docker image linter complains about the multiple RUNs. The error can be suppressed.
> 
> Do I need to check the the failure issue and fix it?

yes, the build has to be clean for this to get in.

2024-01-05 13:53 UTC, vladak commented on Dockerfile
```suggestion
# hadolint ignore=DL3008,DL3059
```

2024-01-05 13:58 UTC, merged

2024-01-05 13:58 UTC, vladak commented
Thanks !